name: Update Dataset

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 7 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dataherb-flora
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Get current directory and files
        run: |
          pwd
          ls
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python Requirements
        run: |
          pip install requests
          pip install pandas
      - name: Download new data
        run: |
          python code/update_data.py
      - name: Update Data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add .
          git commit -m "Update Datasets" || echo "Nothing to update"
          git status
      - name: Push changes to repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
