name: Update Dataset

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 7 * * 1'
  workflow_dispatch:
    inputs:
      whotriggered:
        description: 'Manual Trigger'
        default: 'Why'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dataherb-flora
        uses: actions/checkout@v3
      - name: Get current directory and files
        run: |
          pwd
          ls
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python Requirements
        run: |
          pip install requests==2.31.0
          pip install pandas==2.0.1
      - name: Download new data
        run: |
          python code/update_data.py
      - name: Update charts
        run: |
          pip install plotly==5.14.1
          python code/update_visualization.py
      - name: Update Data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add .
          git commit -m "Update Datasets" || echo "Nothing to update"
          git status
      - name: Push changes to repo
        uses: ad-m/github-push-action@master
        with:
          branch: main
